version: "3"
services:
    db:
        image: postgres:14.3
        ports:
            - "5432:5432"
        environment:
            POSTGRESS_PASSWORD: ${DB_PASSWORD}
            POSTGRESS_DB: ${DB_DATABASE}
        container_name: cursonest
        volumes:
            - ./postgres:/var/lib/postgresql/data
